#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "homebox"
name = "Homebox"

description.en = "A continuation of HomeBox the inventory and organization system built for the Home User"
description.fr = "Une continuation de HomeBox, le système d&#39;inventaire et d&#39;organisation conçu pour l&#39;utilisateur domestique"

version = "16.0~ynh~ynh1"

maintainers = ["hazzamyman"]

[upstream]
license = "AGPL-3.0 license"
website = "https://homebox.software/"
demo = "https://demo.homebox.software/"
admindoc = "https://homebox.software/en/"

code = "https://github.com/sysadminsmedia/homebox"

[integration]
yunohost = '>= 11.2.30'
helpers_version = "2.1"
# List of supported archs using the dpkg --print-architecture nomenclature (amd64/i386/armhf/arm64), for example: ["amd64", "i386']
architectures = "all" 
multi_instance = false
ldap = "not_relevant" 
sso = "false"
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]

    [install.domain]
    # this is a generic question - ask strings are automatically handled by YunoHost's core
    type = "domain"

    [install.path]
    # this is a generic question - ask strings are automatically handled by YunoHost's core
    type = "path"
    default = "/homebox"

    [install.init_main_permission]
    # this is a generic question - ask strings are automatically handled by YunoHost's core
    # This won't be saved as setting and will instead be used to initialize the SSOwat permission
    type = "group"
    default = "visitors"

[resources]
    # See the packaging documentation for the full set
    # of explanation regarding the behavior and properties for each of those
    # https://yunohost.org/packaging_apps_resources

    [resources.sources]

        [resources.sources.main]
        url = "https://github.com/sysadminsmedia/homebox/releases/download/v0.16.0/homebox_Linux_x86_64.tar.gz"
        sha256 = "34d01d3037902deb208ca4a6d8d9b78bf68ea579e0afd566c765783e0067fb32"

        autoupdate.strategy = "latest_github_tag"

    [resources.permissions]
    # This will configure SSOwat permission for $domain/$path/
    # The initial allowed group of user is configured via the init_main_permission question (public=visitors, private=all_users)
    main.url = "/"

    [resources.ports]
    # This will pick a random port for reverse-proxying and store it as the $port setting
    [resources.database]
    # This will automatically provision/deprovision a database and store the corresponding credentials in settings $db_user, $db_name, $db_pwd
    type = "mysql"